/**
 *                          Sun Public License Notice
 *
 * The contents of this file are subject to the Sun Public License Version
 * 1.0 (the "License"). You may not use this file except in compliance with
 * the License. A copy of the License is available at http://www.sun.com/
 *
 * The Original Code is the "Explore from here" NetBeans Module.
 * The Initial Developer of the Original Code is alessandro negrin.
 * Portions created by alessandro negrin are Copyright (C) 2005.
 * All Rights Reserved.
 *
 * Contributor(s): alessandro negrin.
 *
 */
package net.sf.efhnbm.options.spi;

import java.awt.Color;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import net.sf.efhnbm.Launcher;

/**
 * spi option panel
 *
 * @author alessandro negrin
 * @version $Id$
 */
public class EFHOptionPanel extends javax.swing.JPanel {
    
    /** Creates new form EFHOptionPanel */
    public EFHOptionPanel() {
        initComponents();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        optionGroup = new javax.swing.ButtonGroup();
        bundleOption = new javax.swing.JRadioButton();
        classOption = new javax.swing.JRadioButton();
        commandOption = new javax.swing.JRadioButton();
        classTextField = new javax.swing.JTextField();
        commandTextField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(java.util.ResourceBundle.getBundle("net/sf/efhnbm/resources/i18n").getString("option")));
        bundleOption.setBackground(null);
        optionGroup.add(bundleOption);
        bundleOption.setText(java.util.ResourceBundle.getBundle("net/sf/efhnbm/resources/i18n").getString("option.bundle"));
        bundleOption.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        bundleOption.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bundleOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSelectBundle(evt);
            }
        });

        classOption.setBackground(null);
        optionGroup.add(classOption);
        classOption.setText(java.util.ResourceBundle.getBundle("net/sf/efhnbm/resources/i18n").getString("option.class"));
        classOption.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        classOption.setMargin(new java.awt.Insets(0, 0, 0, 0));
        classOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSelectClass(evt);
            }
        });

        commandOption.setBackground(null);
        optionGroup.add(commandOption);
        commandOption.setText(java.util.ResourceBundle.getBundle("net/sf/efhnbm/resources/i18n").getString("option.command"));
        commandOption.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        commandOption.setMargin(new java.awt.Insets(0, 0, 0, 0));
        commandOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSelectCommand(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(bundleOption)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(classOption)
                            .add(commandOption))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(classTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, commandTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(bundleOption)
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(classOption)
                    .add(classTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(commandOption)
                    .add(commandTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
        
    private void onSelectCommand(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSelectCommand
        
        classTextField.setEnabled(false);
        commandTextField.setEnabled(true);
    }//GEN-LAST:event_onSelectCommand
    
    private void onSelectClass(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSelectClass
        
        classTextField.setEnabled(true);
        commandTextField.setEnabled(false);
    }//GEN-LAST:event_onSelectClass
    
    private void onSelectBundle(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSelectBundle
        
        classTextField.setEnabled(false);
        commandTextField.setEnabled(false);
    }//GEN-LAST:event_onSelectBundle
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bundleOption;
    private javax.swing.JRadioButton classOption;
    private javax.swing.JTextField classTextField;
    private javax.swing.JRadioButton commandOption;
    private javax.swing.JTextField commandTextField;
    private javax.swing.ButtonGroup optionGroup;
    // End of variables declaration//GEN-END:variables
    
    JRadioButton getBundleOption(){
        return bundleOption;
    }
    JRadioButton getClassOption(){
        return classOption;
    }
    JRadioButton getCommandOption(){
        return commandOption;
    }
    
    JTextField getClassTextField(){
        return classTextField;
    }
    JTextField getCommandTextField(){
        return commandTextField;
    }
    
}
