/**
 *                          Sun Public License Notice
 *
 * The contents of this file are subject to the Sun Public License Version
 * 1.0 (the "License"). You may not use this file except in compliance with
 * the License. A copy of the License is available at http://www.sun.com/
 *
 * The Original Code is the "Explore from here" NetBeans Module.
 * The Initial Developer of the Original Code is alessandro negrin.
 * Portions created by alessandro negrin are Copyright (C) 2005.
 * All Rights Reserved.
 *
 * Contributor(s): alessandro negrin.
 *
 */
package net.sf.efhnbm.options.spi;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 * spi option panel
 *
 * @author alessandro negrin
 * @version $Id$
 */
public class EFHOptionPanel extends javax.swing.JPanel {
    
    /** Creates new form EFHOptionPanel */
    public EFHOptionPanel() {
        initComponents();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        optionGroup = new javax.swing.ButtonGroup();
        commandChooser = new javax.swing.JFileChooser();
        bundleOption = new javax.swing.JRadioButton();
        classOption = new javax.swing.JRadioButton();
        commandOption = new javax.swing.JRadioButton();
        classTextField = new javax.swing.JTextField();
        commandsPanel = new javax.swing.JPanel();
        commandTextFieldExplore = new javax.swing.JTextField();
        browseCommandButtonSelect = new javax.swing.JButton();
        commandTextFieldSelect = new javax.swing.JTextField();
        browseCommandButtonExplore = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/sf/efhnbm/resources/i18n"); // NOI18N
        setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("option"))); // NOI18N
        bundleOption.setBackground(null);
        optionGroup.add(bundleOption);
        bundleOption.setText(bundle.getString("option.bundle")); // NOI18N
        bundleOption.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        bundleOption.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bundleOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSelectBundle(evt);
            }
        });

        classOption.setBackground(null);
        optionGroup.add(classOption);
        classOption.setText(bundle.getString("option.class")); // NOI18N
        classOption.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        classOption.setMargin(new java.awt.Insets(0, 0, 0, 0));
        classOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSelectClass(evt);
            }
        });

        commandOption.setBackground(null);
        optionGroup.add(commandOption);
        commandOption.setText(bundle.getString("option.command")); // NOI18N
        commandOption.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        commandOption.setMargin(new java.awt.Insets(0, 0, 0, 0));
        commandOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSelectCommand(evt);
            }
        });

        commandsPanel.setBackground(null);

        browseCommandButtonSelect.setText(bundle.getString("browse_command")); // NOI18N
        browseCommandButtonSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                onBrowseForCommandSelect(evt);
            }
        });

        browseCommandButtonExplore.setText(bundle.getString("browse_command")); // NOI18N
        browseCommandButtonExplore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                onBrowseForCommandExplore(evt);
            }
        });

        org.jdesktop.layout.GroupLayout commandsPanelLayout = new org.jdesktop.layout.GroupLayout(commandsPanel);
        commandsPanel.setLayout(commandsPanelLayout);
        commandsPanelLayout.setHorizontalGroup(
            commandsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(commandsPanelLayout.createSequentialGroup()
                .add(commandsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(commandTextFieldExplore, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, commandTextFieldSelect, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(commandsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, browseCommandButtonExplore)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, browseCommandButtonSelect)))
        );
        commandsPanelLayout.setVerticalGroup(
            commandsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(commandsPanelLayout.createSequentialGroup()
                .add(commandsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(browseCommandButtonExplore)
                    .add(commandTextFieldExplore, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(commandsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(browseCommandButtonSelect)
                    .add(commandTextFieldSelect, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(bundleOption)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(classOption)
                            .add(commandOption))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(commandsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, classTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(bundleOption)
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(classOption)
                    .add(classTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(commandOption)
                    .add(commandsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onBrowseForCommandSelect(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onBrowseForCommandSelect
// TODO add your handling code here:
        int result=commandChooser.showOpenDialog(this);
        if (result==JFileChooser.APPROVE_OPTION){
            commandTextFieldSelect.setText(commandChooser.getSelectedFile().getAbsolutePath()+" {0}");
        }
    }//GEN-LAST:event_onBrowseForCommandSelect

    private void onBrowseForCommandExplore(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onBrowseForCommandExplore
        // TODO add your handling code here:
        int result=commandChooser.showOpenDialog(this);
        if (result==JFileChooser.APPROVE_OPTION){
            commandTextFieldExplore.setText(commandChooser.getSelectedFile().getAbsolutePath()+" {0}");
        }
    }//GEN-LAST:event_onBrowseForCommandExplore
        
    private void onSelectCommand(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSelectCommand
        
        classTextField.setEnabled(false);
        
        commandTextFieldExplore.setEnabled(true);
        browseCommandButtonExplore.setEnabled(true);
        commandTextFieldSelect.setEnabled(true);
        browseCommandButtonSelect.setEnabled(true);
        
    }//GEN-LAST:event_onSelectCommand
    
    private void onSelectClass(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSelectClass
        
        classTextField.setEnabled(true);
        
        commandTextFieldExplore.setEnabled(false);
        browseCommandButtonExplore.setEnabled(false);
        commandTextFieldSelect.setEnabled(false);
        browseCommandButtonSelect.setEnabled(false);
        
    }//GEN-LAST:event_onSelectClass
    
    private void onSelectBundle(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSelectBundle
        
        classTextField.setEnabled(false);
        
        commandTextFieldExplore.setEnabled(false);
        browseCommandButtonExplore.setEnabled(false);
        commandTextFieldSelect.setEnabled(false);
        browseCommandButtonSelect.setEnabled(false);
        
    }//GEN-LAST:event_onSelectBundle
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseCommandButtonExplore;
    private javax.swing.JButton browseCommandButtonSelect;
    private javax.swing.JRadioButton bundleOption;
    private javax.swing.JRadioButton classOption;
    private javax.swing.JTextField classTextField;
    private javax.swing.JFileChooser commandChooser;
    private javax.swing.JRadioButton commandOption;
    private javax.swing.JTextField commandTextFieldExplore;
    private javax.swing.JTextField commandTextFieldSelect;
    private javax.swing.JPanel commandsPanel;
    private javax.swing.ButtonGroup optionGroup;
    // End of variables declaration//GEN-END:variables
    
    JRadioButton getBundleOption(){
        return bundleOption;
    }
    JRadioButton getClassOption(){
        return classOption;
    }
    JRadioButton getCommandOption(){
        return commandOption;
    }
    
    JTextField getClassTextField(){
        return classTextField;
    }
    JTextField getCommandTextFieldExplore(){
        return commandTextFieldExplore;
    }
    JButton getBrowseCommandButtonExplore(){
        return browseCommandButtonExplore;
    }
    JTextField getCommandTextFieldSelect(){
        return commandTextFieldSelect;
    }
    JButton getBrowseCommandButtonSelect(){
        return browseCommandButtonSelect;
    }

    
}
